### ISSUE TITLE
Not an issue, but a question.

### ISSUE THREAD

**Issue by Jvp2001** [OndrejSlamecka/slameckacz#1]
I was wondering why the specialisation that takes **E** was necessary for Append. I am using Clang on Windows with MSVC.
```cpp
template <int E, int H, int... T>
struct Append<E, Vector<H, T...>>
{
    using type = typename Prepend<H, typename Append<E, Vector<T...>>::type>::type;
};

template <int E, int... T>
struct Append<E, Vector<T...>>
{
    using type = Vector<E>;
};

// My version
template <Number auto, typename>
struct Append{};


template <int H, int... T>
struct Append<H, Vector<T...>>
{
    using type = Vector<T..., H>;
};
``` 
Mine also works for the test case.

**Comment by OndrejSlamecka** [comment]
I was most likely focused on using the previously defined `Prepend` but your solution is neater and will also be better for compile times (as there's fewer template instantiations).
